# Generated by Django 3.2.6 on 2021-08-31 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.TextField()),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.CharField(max_length=20)),
                ('optional', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('state', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Type_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.main')),
                ('requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.requirement')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('type_requirement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.type_requirement')),
            ],
        ),
        migrations.AddField(
            model_name='main',
            name='register',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.register'),
        ),
    ]
